export const HANDLE_APP_STATE = 'HANDLE_APP_STATE';
export const FETCH_WORDS_FILTRED_START = 'FETCH_WORDS_FILTRED_START';
export const FETCH_WORDS_FILTRED_SUCCESS = 'FETCH_WORDS_FILTRED_SUCCESS';
export const FETCH_WORDS_FILTRED_FAIL = 'FETCH_WORDS_FILTRED_FAIL';
