export const HANDLE_QUERY = 'HANDLE_QUERY';
export const FETCH_WORDS_QUERY_START = 'FETCH_WORDS_QUERY_START';
export const FETCH_WORDS_QUERY_SUCCESS = 'FETCH_WORDS_QUERY_SUCCESS';
export const FETCH_WORDS_QUERY_FAIL = 'FETCH_WORDS_QUERY_SUCCESS';
export const FETCH_WORDS_FILTRED_START = 'FETCH_WORDS_FILTRED_START';
export const FETCH_WORDS_FILTRED_SUCCESS = 'FETCH_WORDS_FILTRED_SUCCESS';
export const FETCH_WORDS_FILTRED_FAIL = 'FETCH_WORDS_FILTRED_FAIL';
